const MissionCommander = require('./app/missionCommander')
const juan = new MissionCommander("Juan")
const william = new MissionCommander("Will")
const owen = new MissionCommander("El Nene")
console.log(juan.name)
console.log(william.name)
console.log(owen.name)